# Site settings
title: United Code Unlimited
header-img: img/home-bg.jpg
email: unitedcodeunlimited@gmail.com
description: "Flix2You"
baseurl: ""
url: "http://unitedcodeunlimited.github.io"
twitter_username: 
github_username:  unitedcodeunlimited
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
